  - name: Enable Redis module using DNF
    ansible.builtin.command: dnf module enable redis:remi-6.2 -y
      
  - name: Install nginx rpm from a local file
    ansible.builtin.dnf:
      name: redis
      state: latest
    

  # - name : Installing {{COMPONENT}}
  #   ansible.builtin.package:
  #     name: mongodb-org
  #     state: present

  # - name: Enabling {{COMPONENT}} visibility
  #   ansible.builtin.replace:
  #    path: /etc/mongod.conf
  #    regexp: '127.0.0.0'
  #    replace: '0.0.0.0'

  # - name: Restarting {{COMPONENT}} service
  #   ansible.builtin.systemd_service:
  #     name: mongod
  #     state: started
  #     enabled: yes
  #     daemon_reload: true

