  - name: Configuring {{COMPONENT}} repository
    ansible.builtin.copy:
       src: mongo.repo                      # Location of the file on the machine where youare running the script
       dest: /etc/yum.repos.d/mongodb.repo  # Location of the file where you want to copy this to remote server

  - name : Installing {{COMPONENT}}
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: Enabling {{COMPONENT}} visibility
    ansible.builtin.replace:
     path: /etc/mongod.conf
     regexp: '127.0.0.0'
     replace: '0.0.0.0'

  - name: Restarting {{COMPONENT}} service
    ansible.builtin.systemd_service:
      name: mongod
      state: started
      enabled: true
      daemon_reload: true

  - name: Download and Extracting {{COMPONENT}}
    ansible.builtin.unarchive:
      src: https://github.com/stans-robot-project/mongodb/archive/main.zip
      dest: /tmp
      remote_src: yes    