- name : Installing {{COMPONENT}}
  ansible.builtin.package:
      name: maven
      state: present

- name: Creating {{APPUSER}} user
  ansible.builtin.user:
    name: "{{APPUSER}}"

- name: Download and Extracting {{COMPONENT}}
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Performing Cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent

- name: Copying {{COMPONENT}} to {{APPUSER}}
  ansible.builtin.copy:
      src: /tmp/{{COMPONENT}}-main/
      dest: /home/{{APPUSER}}/{{COMPONENT}}/
      owner: "{{APPUSER}}"
      group: "{{APPUSER}}"
      remote_src: yes

# - name: Copying {{COMPONENT}} systemd file
#   ansible.builtin.template:
#     src: systemd.service
#     dest: /etc/systemd/system/{{COMPONENT}}.service