# In ansible if you attempt to print a variable which is not declared will throw an exception

- name: Demo on variables 
  hosts: all
  vars: 
    URL: Play.google.com  # global variable
  vars_files:
    - "{{ENV}}.yaml"
  tasks:
   - name: Printing the variable
     ansible.builtin.debug:
      msg: Value of the URL is {{URL}}

   - name: Printing the variable
     ansible.builtin.debug:
      msg: Value of the XYZ is {{URL}}
     vars: 
       URL: task.google.com  #task level or local variable
  
   - name: Printing the variable from Command Line
     ansible.builtin.debug:
      msg: Value of the URL is {{XYZ}}
     ignore_errors: true

   - name: Printing the ENC specific values
     ansible.builtin.debug:
      msg: "Instance Type is {{INSTANCE_TYPE}} and disk size is {{DISK_SIZE}}"

# Variable precedence : Command Line > local variable > Global variables 

# 