# In ansible if you attempt to print a variable which is not declared will throw an exception

- name: Demo on variables 
  hosts: all
  vars: 
    URL: Play.google.com  # global variable
  tasks:
   - name: Printing the variable
     ansible.builtin.debug:
      msg: Value of the URL is {{URL}}

   - name: Printing the variable
     ansible.builtin.debug:
       msg: Value of the XYZ is {{XYZ}}
     vars: 
       URL: task.google.com  #task level or local variable