- name: demo on using shelll commands
  hosts: all
  tasks:
    - name: Running uptime commands
      ansible.builtin.shell: uptime         #shell module wont offer output buy default, need to register if required
      register: OUT
    - name: printing system uptime
      ansible.builtin.debug:
        msg: The system uptime is {{OUT.stdout}}

    # - name: Capturing the exit code using set_fact
    #   set_fact: 
    #     EXITCODE: "{{OUT.rc}}"

    - name: printing exit code 
      ansible.builtin.debug:
        msg: "Exit code is {{OUT.rc}}"