- name: Demo on Errors
  hosts: all
  tasks:
    - name: Chcek toomcat is running or not
      ansible.builtin.shell: ps -ef | grep java |grep -v grep
      register: OUT

    - name: Run the shipping
      ansible.builtin.debug:
       msg: " shipping is up"
