- name: Demo on conditions
  hosts: all
  vars:
    action: true
  tasks:
    - name: Run this task when os distro is centos only
      ansible.builtin.debug:
       msg: OS Distribution is {{ansible_distribution}}
      when: ansible_distribution == "CentOS"

    - name: Run this task when the Distro is Ubuntu only
      ansible.builtin.debug:
       msg: OS Distribution is {{ansible_distribution}}
      when: ansible_distribution == "Ubuntu"