- name: demo on privilage escalation
  hosts: all
  become: yes         # Run the playbook as root user, this like running the playbook as sudo
  tasks:
    - name: Running uptime commands
      ansible.builtin.shell: id         #shell module wont offer output buy default, need to register if required
      register: OUT                         # Output will be register in a variable called OUT, which can be used in any of the tasks of the play

    - name: printing the detals
      ansible.builtin.debug:
        msg: Username is {{OUT.stdout}}