- name: demo on privilage escalation
  hosts: all
  tasks:
    - name: Running uptime commands
      ansible.builtin.shell: id         #shell module wont offer output buy default, need to register if required
      register: OUT                         # Output will be register in a variable called OUT, which can be used in any of the tasks of the play

    - name: printing the detals
      ansible.builtin.debug:
        msg: The system uptime is {{OUT.uid}}