# Demo on copying the files to remote servers
- name: Demo on file copy
  hosts: all 
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
       src: ansible/agenda
       dest: /home/cenos/
 