# Demo on copying the files to remote servers
- name: Demo on file copy
  hosts: all 
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
       src: agenda
       dest: /home/centos/ansi/agenda

    - name: Create a directory if it does not exist
      ansible.builtin.file:
       path: /home/centos/ansi
       state: directory
       mode: '0755'

 