# prerequisite : the machine that you are running this should have ansible installed.

- name: Configuring roboshop project
  hosts: localhost  # This defines playbook will be executed on top of the same machine only
  become: True
  roles:
    - role: "{{COMPONENT}}"