  - name: Configuring {{COMPONENT}} ERLANG dependencies
  # - name: Installing ERLANG 
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

  - name: Configuring the {{COMPONENT}} repo
    ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

  - name : Installing {{COMPONENT}}
    ansible.builtin.package:
      name: rabbitmq-server
      state: present

  - name: Starting {{COMPONENT}} service
    ansible.builtin.systemd_service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: Create user account in {{COMPONENT}} database
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present

  - name: Configuring hostname and environment name
    ansible.builtin.include_role:
      name: common
      tasks_from: set_hostname