
  - name : Removing mysql 8 from {{COMPONENT}} 
    ansible.builtin.package:
      name: mysql
      state: absent

  - name: Configuring {{COMPONENT}} repository
    ansible.builtin.copy:
      src: mysql.repo                      # Location of the file on the machine where youare running the script
      dest: /etc/yum.repos.d/mysql.repo  # Location of the file where you want to copy this to remote server

  - name : Installing {{COMPONENT}} package
    ansible.builtin.package:
      name: 
        - mysql-community-server
        - python3-PyMySQL
        - MySQL-python
      state: present
     
  - name: Restarting {{COMPONENT}} service
    ansible.builtin.systemd_service:
      name: mysqld
      state: started
      enabled: yes


  - name: Extracting the mysql log file
    ansible.builtin.slurp:
      src: /var/log/mysqld.log
    register: pws_log

  # - name: Printing the password file
  #   debug:
  #     msg: " {{pws_log['content'] | b64decode | regex_findall('.*temporary password.*')| join(' ') | split(' ') | last}}"

# Note- If any of the task in the block fails, tasks in the rescue will be executed
  - name: Verifying the password
    block:
      - name: Get MySQL version with non-default credentials
        community.mysql.mysql_info:
          login_user: root
          login_password: "{{MYSQL_PWD}}"
          filter: version
    rescue:
      - name: Extracting password from logfile
        ansible.builtin.set_fact:
          DEFAULT_PASSWORD: "{{pws_log['content'] | b64decode | regex_findall('.*temporary password.*')| join(' ') | split(' ') | last}}"

      - name: Changing default root password
        ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Roboshop@1'" | mysql --connect-expired-password -uroot -p"{{DEFAULT_PASSWORD}}"

      - name: Uninstall Password Validate Plugin
        ansible.builtin.shell: echo "uninstall plugin validate_password;" | mysql -uroot -pRoboshop@1
      
# What to do:
# 1) lets try to get the DB details by sinin in with Roboshop@1
# 2) if you dont get the info, change the password

# to handle the above scnario we have set of modules called Block and rescue" if any of the tasks of the block failled rescue will be executed.

