  - name: Disable Default repo and MYSQL 8
    ansible.builtin.dnf:
      name: mysql
      state: absent
  
  - name: Configuring {{COMPONENT}} repository
    ansible.builtin.copy:
       src: mysql.repo                      # Location of the file on the machine where youare running the script
       dest: /etc/yum.repos.d/mysql.repo  # Location of the file where you want to copy this to remote server

  - name : Installing {{COMPONENT}}
    ansible.builtin.dnf:
      name: mysql-community-server
      state: present
  
  - name: Restarting {{COMPONENT}} service
    ansible.builtin.systemd_service:
      name: mysqld
      state: started
      enabled: yes

  - name: Find out what the remote machine's mounts are
    ansible.builtin.slurp:
      src: /proc/mounts
      register: mounts