
  - name : Removing mysql 8 from {{COMPONENT}} 
    ansible.builtin.package:
      name: mysql
      state: absent

  - name: Configuring {{COMPONENT}} repository
    ansible.builtin.copy:
       src: mysql.repo                      # Location of the file on the machine where youare running the script
       dest: /etc/yum.repos.d/mysql.repo  # Location of the file where you want to copy this to remote server

  - name : Installing {{COMPONENT}} package
    ansible.builtin.package:
      name: mysql-community-server
      state: present
     
  - name: Restarting {{COMPONENT}} service
    ansible.builtin.systemd_service:
      name: mysqld
      state: started
      enabled: yes


  - name: Extracting the mysql log file
    ansible.builtin.slurp:
      src: /var/log/mysqld.log
    register: pws_log

  # - name: Printing the password file
  #   debug:
  #     msg: " {{pws_log['content'] | b64decode | regex_findall('.*temporary password.*')| join(' ') | split(' ') | last}}"

  - name: Extracting password from logfile
    ansible.builtin.set_fact:
      DEFAULT_PASSWORD: "{{pws_log['content'] | b64decode | regex_findall('.*temporary password.*')| join(' ') | split(' ') | last}}"

  - name: Changing default root password
    ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Roboshop@1'" | mysql --connect-expired-password -uroot -p$DEFAULT_PASSWORD