- name: Remove the Nodejs 10 package
  ansible.builtin.dnf:
    name: nodejs
    state: absent

- name: Install latest Nodejs 18 package
  ansible.builtin.dnf:
    name: nodejs:18
    state: present

  # - name : Disabling the default nodejs:10 repo
  #   ansible.builtin.package:
  #     name: nodejs.18
  #     state: present

