- name: Copying {{COMPONENT}} systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Starting {{COMPONENT}} service
  ansible.builtin.systemd_service:
    name: "{{COMPONENT}}"
    state: started
    enabled: yes
    daemon_reload: yes