- name : Installing {{COMPONENT}}
  ansible.builtin.package:
      name: maven
      state: present

- name: Configuring {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Download and Extract {{COMPONENT}} artifacts
  ansible.builtin.include_role:
    name: common
    tasks_from: dwonload_and_extract

- name: Generating {{COMPONENT}} artifacts
  ansible.builtin.shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}

- name: Configuring and starting {{COMPONENT}} service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc