- name : Installing Node JS in {{COMPONENT}}
  ansible.builtin.package:
    name: nodejs
    state: present


- name: Configuring {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Download and Extract {{COMPONENT}} artifacts
  ansible.builtin.include_role:
    name: common
    tasks_from: download_and_extract

- name: Generating {{COMPONENT}} artifacts
  community.general.npm:
     path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Configuring and starting {{COMPONENT}} service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: Configuring hostname and environment name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_hostname
