- name : Installing NodeJS in {{COMPONENT}}
  ansible.builtin.package:
    name: nodejs
    state: present


- name: Configuring User Account
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

###------ Uncomment it if you want the artifact from Github
# - name: Download and Extract {{COMPONENT}} artifacts
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: download_and_extract

- name: Download and Extract {{COMPONENT}} artifacts from Nexus
  ansible.builtin.include_role:
    name: common
    tasks_from: download_from_nexus

#####----- Uncomment it if you want the artifact from Github
# - name: Generating {{COMPONENT}} artifacts
#   community.general.npm:
#      path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Configuring and starting {{COMPONENT}} service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: Configuring hostname and environment name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_hostname
