- name : Installing Python3 
  ansible.builtin.package:
    name:
      - python36
      - gcc 
      - python3-devel
    state: present

- name: Configuring {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Download and Extract {{COMPONENT}} artifacts
  ansible.builtin.include_role:
    name: common
    tasks_from: download_and_extract


- name: Updating the UID in {{COMPONENT}}.ini file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini 
    regex: '^uid'
    line: uid = {{USERINFO.uid}}

- name: Updating the UID in {{COMPONENT}}.ini file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini 
    regex: '^gid'
    line: gid = {{USERINFO.group}}

- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: /home/{{APPUSER}}/{{COMPONENT}}/requirements.txt
    executable: pip3.6

- name: Configuring and starting {{COMPONENT}} service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: Configuring hostname and environment name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_hostname
